# Generated by Django 5.2 on 2025-04-13 01:25

from django.db import migrations

def apply_migration(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    arr_permissions = []
    arr_operation = ["add", "change", "delete", "view"]
    models = ["customuser", "category", "address", "product", "image", "variant"]

    admin = Group(name="admin")
    admin.save()

    for model in models:
        for operation in arr_operation:
            admin.permissions.add(Permission.objects.get(codename=f"{operation}_{model}"))


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0002_category_product_image_variant'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
