# Generated by Django 5.2 on 2025-04-13 01:25
from django.contrib.auth.management import create_permissions
from django.db import migrations

def apply_migration(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)

    arr_permissions = []
    arr_operation = ["add", "change", "delete", "view"]
    models = ["customuser", "category", "address", "product", "image", "variant"]

    admin = Group(name="admin")
    admin.save()

    for model in models:
        permissions = Permission.objects.all()
        for permission in permissions:
            admin.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0002_category_product_image_variant'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
