# Generated by Django 5.2 on 2025-04-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0003_auto_create_admin_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='type',
            new_name='role',
        ),
    ]
