# Generated by Django 5.2 on 2025-04-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0005_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'name')},
        ),
    ]
