# Generated by Django 5.2 on 2025-06-10 21:50

from django.db import migrations
import os
import json
from django.conf import settings

from kyroshop.models.province import Province
from kyroshop.models.city import City

def apply_migration(apps, schema_migration):
    provinces_file = open(os.path.join(settings.BASE_DIR, 'kyroshop/data/provinces.json'))
    regencies_file = open(os.path.join(settings.BASE_DIR, 'kyroshop/data/regencies.json'))

    provinces_data = json.load(provinces_file)
    regencies_data = json.load(regencies_file)

    for data in provinces_data:
        province = Province.objects.get_or_create(id=str(data['id']), name=data['province'])

    for data in regencies_data:
        province = Province.objects.get(id=str(data['province_id']))
        city = City.objects.get_or_create(id=str(data['id']), type=data['type'], name=data['regency'], province=province)

class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0009_province_city'),
    ]

    operations = [
        migrations.RunPython(apply_migration),
    ]
