# Generated by Django 5.2 on 2025-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0012_product_seo_description_product_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
