# Generated by Django 5.2 on 2025-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0013_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('JNE', 'JNE'), ('JNT', 'JNT')], default='JNE', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CHECK_OUT', 'Check Out'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('RETURNED', 'Returned'), ('DONE', 'Done')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
