# Generated by Django 5.2 on 2025-07-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyroshop', '0014_order_payment_method_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('CHECK_OUT', 'Check Out'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('RETURNED', 'Returned'), ('DONE', 'Done')], default='SAVED', max_length=10),
        ),
    ]
