from .register_view import RegisterView
from .category_view import CategoryView
from .profile_view import ProfileView
from .product_view import ProductView
from .image_view import ImageUploadView
from .customer_view import CustomerView
from .order_view import OrderView
from .orders_view import OrdersView
from .province_view import ProvinceView
from .city_view import CityView